---
title: "A beginner's guide to UQÀM and Canada"
author: "CarBBAS"
date: "Last updated on: 06 May 2020"
output:
  html_document:
    toc: true
    toc_depth: 3
---

---

# A few words
Welcome! You are joining UQÀM and you are heading towards an adventure to live in Montréal. This is a list of things that you need to do before and after ariving in Montréal and other things are just for informative purposes. Information given here are merely a help for you to go through the sometimes a bit overwhelming steps until you get settled with us. This list is not a definitive instruction, we will try to keep the points and links updated to its best but be aware that things may change and information are not 100% accurate anymore. If there is something unclear, don't hesitate to contact any of the current lab members.

---

# Students
## Before arrival
### UQÀM registration
To register to UQÀM, you have to fill in several forms. Now, you can also apply online instead of sending the documents by post!
You can find a step guide [here](https://etudier.uqam.ca/etudiants-etrangers). It is in French, but you can make use of Google Chrome and the automatic google translate option.

You’ll need to find the program number for a

* [Masters in biology](https://etudier.uqam.ca/programme?code=3440) (No. 3440)
OR
* [Doctorate in biology](https://etudier.uqam.ca/programme?code=3805) (No. 3805)
    
As mentioned above, admission can be done [online now](https://etudier.uqam.ca/admission-en-ligne). You can find the documents that will be needed [here](https://etudier.uqam.ca/documents-requis). Essentially, you will need your transcripts from previous degrees (in French or English), copy of your diploma and other UQÀM forms that need to be filled. And you have to pay the admission fee of around $126 by credit card.

> **Tip**: Make sure that your passport is valid for several years! You cannot get the CAQ and study permit for longer than your passport is valid. Otherwise you will need to renew your passport and get an extension while you’re studying (and pay the fee again).

---

### CAQ
Before you can apply to a study permit, you’ll need the **CAQ** (Certificat d'acceptation du Quebec) which allows you to study in Québec.

UQÀM is a designated learning institution (DLI# O19359011134) or check [here](https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit/prepare/designated-learning-institutions-list.html) for more details. So once, you have the letter of admission from UQÀM, you can apply fairly easily. Check the steps for CAQ application [here](http://www.immigration-quebec.gouv.qc.ca/en/immigrate-settle/students/obtaining-authorizations/certificat-acceptation/index.html).

You can [apply online](http://www.immigration-quebec.gouv.qc.ca/en/electronic-services/caq-electronic/index.html) and you will need:

* a recent ID photo (35 mm x 45 mm)
* photocopy of your passport
* letter of admission from the registrar
* pay the processing fee (~CAD$114)

Processing times vary. The average is 20 days.

---

### Study permit
Once you have received the **CAQ**, you can apply for the **study permit**. Application to a study permit depends largely on which country you are from. Consult the website of the [Government of Canada](https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html) for further instructions.

For sure is, you will have to pay around CAD$150 and processing times vary depending on where you apply from. Check processing times [here](https://www.canada.ca/en/immigration-refugees-citizenship/services/application/check-processing-times.html). You will need to provide:

* a photocopy of your passport (for some countries you need to send your passport to a Canadian embassy)
* CAQ approval
* UQÀM admission letter
* a financial support letter from your supervisor or a confirmation of your scholarship

You may need to do medical exams and get police certificates depending on your country of origin. Consult what you need by proceeding in the online application [here](https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit/apply.html).

---

> **Tip**: We recommend you to bring a buffer of cash to survive for at least a month or two, because processing times until UQÀM makes the first payment takes time (~5 weeks)!

> **Tip**: Finding apartments from abroad is tricky. Sometimes students/post-docs leave at the same time as you arrive, so you can ask around. Otherwise, we recommend to book an AirBnb for a month and explore which neighbourhood you like.

---

## After arrival
First of all, the biology department is not located at the main UQÀM campus close to Berri-UQÀM station but at the Science campus close to Place-des-arts (Green Line) metro station. Our offices are located in the the SB building on the second floor. So don’t get lost.

Here are some things you need to do or should know to get started:

---

### 1. Get a Social insurance number (SIN)
You will need to get your social insurance number (SIN) and provide it to UQÀM. To get your SIN, go to:

>*Service Canada*
>
>*Guy-Favreau Complex, Suite 034*
>
>*200 René-Lévesque Boulevard West*
>
>*Open Mon-Fri 8:30 am – 4 pm*

Accessible through the underground from Place-des-arts (Green Line) or Place-d’Armes (Orange line) metro stations.

You will have to bring:

* your passport with the study permit
* fill out their form

Check further information [here](https://www.canada.ca/en/employment-social-development/services/sin/before-applying.html#primary).

> **Tip**: Whenever you renew your study permit, you need to update your social insurance number, too!

---

### 2. Bring documents to UQÀM registrariat
If you were admitted with a condition (provide proof of graduation from BSc or MSc if you applied before graduating), bring the documents to the [UQÀM registrariat](https://etudier.uqam.ca/coordonnees-registrariat).

>Pavillon J.-A.DeSève
>
>Local DS-R110
>
>320 Rue Sainte-Catherine Est
>
>Open Mon-Tue 9 am – 6 pm, Wed-Fri 10 am – 5 pm

It should say in your acceptance letter what documents you need. Bring **three copies** of each document that you have to provide. Be aware that people at the registrariat *are not allowed to speak English*. Gesture and a few before-hand translated words will help you getting what you need. Sometimes you’re lucky and the person doesn’t care. But don’t count on it.

---

### 3. Submit stipend form
Once the main things have been settled, fill out form "Demande de Versement de Bourse" (Scholarship Payment Request). 
**Physically**, you can find this form in the biology department room in PK building, then ask Alice Parkes (for Paul’s student) or Yves Prairie to sign the form to receive your stipend, and submit it to the same biology office that you get the form from. 
**Virtually**, you can send your personal information in an email from your UQAM email address to your director so that they can forward this request to Financial services.

Information/Documents you need to submit the stipend form:

* A photocopy/scan of your study permit
* A photocopy/scan of the first page your passport
* Full name
* Social Insurance Number (SIN)
* UQAM Permanent code
* DOB
* Current address with postal code
* Phone number

It can take more than a month (typically five weeks) until you receive your first payment!
You can sign up for direct deposit [here](https://www.rhu.uqam.ca/index.aspx?id=p710).

Proceed as *‘Sans nom d’utilisateur (code MS)’*. It may not work at first if your SIN is not registered with the UQÀM registrariat yet.

---

### 4. Student Card
Get a student card to get access to student benefits and the gym. Make sure to bring your passport and they will make a picture on-site. Consult opening hours [here](http://ech.uqam.ca/2016-08-02-22-07-10/carte-uqam/horaire-et-coordonnees.html). The place is one floor down of the UQÀM registrariat in the UQÀM main campus.

---

### 5. Access UQÀM Online Portal for students
There is an [online portal](https://portailetudiant.uqam.ca/) where we have all the necessary information that we need (tuition to be paid, courses etc.). To access this you will need:

* Code permanent (should be in your acceptance letter or when you applied online)
* NIP

If you do not have any of this information, consult the UQÀM registrariat.

---

### 6. Access to UQÀM email
Get your code MS [here](https://code.uqam.ca/simplesaml/module.php/core/loginuserpass.php?AuthState=_f48a2d8e5f41af83ca172569f190a0df81f42890c6%3Ahttps%3A%2F%2Fcode.uqam.ca%2Fsimplesaml%2Fsaml2%2Fidp%2FSSOService.php%3Fspentityid%3Dcode.uqam.ca%26RelayState%3Dhttps%253A%252F%252Fcode.uqam.ca%252Fsimplesaml%252Fmodule.php%252Fuqam%252Fstatus.php%26cookieTime%3D1575498828).

You will need your:

* Code permanent
* NIP

Log-in to your UQÀM microsoft account [here](https://login.microsoftonline.com/common/oauth2/authorize?client_id=00000002-0000-0ff1-ce00-000000000000&redirect_uri=https%3A%2F%2Foutlook.office.com%2Fowa%2F&resource=00000002-0000-0ff1-ce00-000000000000&response_mode=form_post&response_type=code+id_token&scope=openid&msafed=0&client-request-id=31a16e0a-7920-4f81-9bf0-f6d4886043e7&protectedtoken=true&domain_hint=uqam.ca&nonce=636892913045285974.37c448c6-87e9-4ae1-8821-a29c70c3a44e&state=DcsxDoAwCEBRqqtXqW2BFjgOIR2NcTBe3w7vbz8BwL5sS6orIIOGGlqjyh21m_BJEswaI6tMy-yzZVVs2dFCapAzz7Teo9yfl_fx6wz_AQ). The password is the *first three letters of your surname in captial + NIP* (e.g. UQA00000).

---

### 7. Opus card for students
To get a cheaper faire for the public transport, get a student opus card. You will be able to purchase a cheaper 4-month pass.

Log-in to the *portail étudiant*. Go to ‘Attestation carte OPUS’. Click the semester of interest and click on ‘Obtenir la carte opus étudainte par la poste’. You can only do this if you have your student card already. With this, you can let your OPUS card be shipped to your home.

If you need to get your card more urgently, you can go to the OPUS student office close to Berri-UQÀM metro station. You will need be able to log-in on-site to the *portail étudiant* to show your document.

---

### 8. Pay tuition
#### Master
As an international Master student, one has to pay the extra fee for foreign students. To get exempt of this, apply to an exemption scholarship on [RIBÉ](https://www.apps.uqam.ca/application/bourses/login/login.aspx). Log-in with your:

* Code permanent
* NIP

You have to fill out *'Mon profil'* and validate the profile with the button on the top left corner. You can fill your profile in French or English. Although French might reveal more appealing to the reviewers of the scholarships (e.g. UQÀM foundation).

Go to *"Recherche bourses"* and look for a foreigner student fee exemption scholarship and apply.

If you do not get the exemption scholarship, ask your supervisor to write you a cheque with the amount of tuition that needs to be paid.

In case you have received the exemption scholarship, the amount will automatically be removed from your tuition bill on the *portail étudiant* and you just need to pay the rest.

---

#### PhD
To pay your tuition go to the *portail étudiant* and follow these steps:

* Click on *‘Factures courante et solde’*
* Scroll down the *‘Facture’* of the next semester
* Click on the ‘+’ next to *Scolarité 3e cycle*
* From the *‘Total’* amount at the very bottom of the page, subtract the *‘Frais majorés étudiant étranger’*

This will be the amount that you need to pay. 

Make sure to provide your *‘Code de paiement’* listed at the beginning of the page when you make the payment via bank transfer. Expect a tuition between 1000 - 2800$ depending on which semester. Usually, you pay more in the autumn semester, because one pays additionally the health insurance.

---

### 9. Register to a class
Each semester, you have to register for a course. To do so, send an email to [Biology Department email address](cyclesupbiologie@uqam.ca) (cyclesupbiologie@uqam.ca) with the code for the course.

#### Master
A Master's in Biology (3440) degree requires four courses (12 credits): Two mandatory and two of choices from multiple offered courses.
Mandatory courses:
* BIO8501 Methodology in biology
* BIO8071 Research seminar

For more information about the courses offered, visit the website for Master's in Biology program [3440] (https://etudier.uqam.ca/programme?code=3440)

---

#### PhD
Usually, a PhD starts with:

* BIO9000 Thesis proposal

Followed by 'ACTIF EN RECHERCHE' in the semesters where you do not take courses but do lab or office work. Other courses that have to be taken are:

* ADM9001 Human resources
* DDD9667 Teaching
* BIO9010 Synthesis exam
* BIO9020 Seminar
* Thesis

Be aware that Human resources and Teaching are taught in French. Both courses allow you to write the final home work in English at this moment. But make sure to check with your professor.

---

### 10. Scholarships
You can apply to several scholarships after you have been admitted to UQÀM as an international student.

* [Vanier](https://vanier.gc.ca/)
* [FRQNT](http://www.frqnt.gouv.qc.ca/en/accueil)
* [PBEEE](https://ssa.uqam.ca/nos-services/bourses/bourses-dexcellence/pbeee.html)

All three of these scholarships are highly competitive and usually there is an internal UQÀM pre-selection. Do not mix up and miss the internal deadline before the overall deadline.

There are several smaller scholarships from UQÀM. Check each semseter what scholarships you can apply to on [RIBÉ](https://www.apps.uqam.ca/application/bourses/login/login.aspx).

---

### 11. Health insurance
You will get a health insurance card by e-mail once you’ve paid your first tuition. It is a private insurance provided by **Desjardins**. You can check what is covered in [this leaflet](https://vie-etudiante.uqam.ca/medias/fichiers/vous-etes_etudiant-etranger/Q178_en_br_Foreign_University_Students.pdf). As a foreign student, you do not have access to the Québec insurance called *RAMQ* (except a few exemption countries such as France and Belgium).

Usually, the insurance card will be sent to you within a month after paying the tuition. However, this means that you're not covered by an insurance until you have your card. Make sure to be covered by a travel insurance from your country of origin (e.g. [blue cross](http://www.bluecross.ca/en/index.html)) or take a private insurance (e.g. [Desjardins](https://www.desjardinslifeinsurance.com/en/individual-insurance/life-health-disability-insurance/health-disability-insurance/healthcare-insurance)) to live through this un-covered period without being worried constantly.

You can get access to an online account of Desjardins to ask for reimbursement of medical expenses [here](https://auth.desjardins.com/Account/SignIn?ReturnUrl=%252fissue%252fwsfed%253fwa%253dwsignin1.0%2526wtrealm%253dhttp%25253a%25252f%25252fsession.desjardins.com%25252fadfs%25252fservices%25252ftrust%2526wctx%253d5cb0841a-41a3-4e94-ae34-dace07d7486a%2526wct%253d2020-01-03T21%25253a45%25253a17Z%2526whr%253dhttp%25253a%25252f%25252fauth.desjardins.com%25252ftrust%25252finitial%2526owtrealm%253dhttps%25253a%25252f%25252fICA%2526owctx%253drm%25253d0%252526id%25253dpassive%252526ru%25253d%2525252fAGEA-GBIM%2525252fAthntfctn%2525252fAccl%2525252fAccueil_Home.aspx%2526fav%253dhttps%25253a%25252f%25252fsession.desjardins.com%25252fadfs%25252fls%25252f%25253fwa%25253dwsignin1.0%252526wtrealm%25253dhttps%25253a%25252f%25252fICA%252526wctx%25253drm%25253d0%252526id%25253dpassive%252526ru%25253d%252525252fAGEA-GBIM%252525252fAthntfctn%252525252fAccl%252525252fAccueil_Home.aspx%252526wct%25253d2020-01-03T21%25253a45%25253a17Z%252526whr%25253dhttp%25253a%25252f%25252fauth.desjardins.com%25252ftrust%25252finitial%252526wreply%25253dhttps%25253a%25252f%25252fwww.agea-gbim.dsf-dfs.com%25252fAGEA-GBIM%25252fDefault.aspx). You can create an account once you have your insurance card. If you have any questions, you can always contact them with the online form. They usually respond quite quickly.

---

#### When you need to go to a doctor
The system works here, that usually you need to go to a generalist first and get a referal. So, usually people see their family doctor. It is hard to find a family doctor in Montréal, however, there are several walk-in clinics for people without a family doctor. Some walk-in clinics are without appointments (expect long waiting hours) or with appointment.

To get an appointment in a walk-in clinic consult their homepage. Usually, you can only get an appointment for the next day. Most clinics use an appointment system called *‘Bonjour-Santé’*. Whenever you need to provide your RAMQ information insert ‘XXXXDDMMYYYY’ instead, where DDMMYYYY is replaced by your birth date. And you can provide any date in the future for the expiration date. You will have to pay a fee for your appointment, which can vary by clinic. Make sure to call and ask before.

To give you an example:

* [**Forcemedic clinics**](https://www.forcemedic.com/)
  (Payment: $160, Appointment registration start: 7 pm the day before)
* [**Clinique 1851**](https://l.facebook.com/l.php?u=https%3A%2F%2Fbonjour-sante.ca%2FTriathlon%2F%3Ffbclid%3DIwAR3yjRyvwA-1nCvhfYWK1_SrOLrsKW8FLqyzRfq8wXWheW15K47fVSMZ81Q%23%2Fidentification%2F1851&h=AT3eQ9dsRykT4e77GQvh1BgOaPgMRisjhPshA7ox6CH8Bs7xjw-1V2aUhZvyE6T7DhoUyT7qNJLt377roOL7ygnQTheeAZR7Z-QjYFzXQfoqbmhDlhGuaQis1us) (Payment: ?, Appointment registration start: 8 pm the day before)

---

### 12. Travel insurance
Be aware that the Desjardins insurance *does not* cover you for more than **14 days** of travel outside of Canada, U.S. or your home country. Whenever you go somewhere else or more than 14 days within those three countries make sure to get a separate travel insurance. Internships in a foreign country that are recognised by the university are covered up to **120 days**.

We **cannot** apply for most of the travel insurance because we do not have the *RAMQ* (e.g. blue cross etc). Find an international travel insurance such as [April](https://www.april.ca/) or [IMG](https://www.imglobal.com/?gclid=CjwKCAiA6bvwBRBbEiwAUER6JQQLPD5IGwkprlG7gY2alZ1CXagiqUcVEy5FpmXOtS6UnyqehiTy3xoCrQMQAvD_BwE).

---

### 13. Driving licence
Students are allowed to use the driving license of their origin of country as long they have an official translation of it if it is not indicated in French or English. For more information, check the [SAAQ](https://saaq.gouv.qc.ca/).

---

# Post-docs (and research internship)
## Before arrival
### UQÀM
?

---

### Work permit
You will need to apply for a **work permit**. Application for a work permit depends largely on which country you are from. Consult the website of the [Government of Canada](https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/permit/temporary/work-permit-types.html) for further instructions.

For sure is, you will have to pay around $155 and processing times vary depending on where you apply from. Check processing times [here](https://www.canada.ca/en/immigration-refugees-citizenship/services/application/check-processing-times.html).

As an academic, you are eligible for an *employer-specific work* permit.

Before you submit your work permit application, your employer must:

* submit an offer of employment to Immigration, Refugees and Citizenship Canada,
* pay a $230 employer compliance fee, and
* provide you with an offer of employment number

**Note**: When you complete your work permit application, select “Exemption from Labour Market Impact Assessment” as the type of work permit in the “Details of intended work in Canada” section.

You will need to provide:

* a photocopy of your passport (for some countries you need to send your passport to a Canadian embassy)
* Proof of employment in Canada (The Offer of Employment number)
* Proof that you are eligible for the job 
* No CAQ is needed because you do not need a Labour Market Impact Assessment (LMIA)
* Other documents if you bring a spouse

You may need to do medical exams and get police certificates depending on your country of origin. Consult what you need by proceeding in the online application [here](https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/permit/temporary/apply.html).

---

### Bringing a partner
If you and your partner have decided to move together to Montréal, he/she needs to apply for an **open** work permit. This application is also exempted from the CAQ.

The most advisable thing to do is to apply together for both work permits at the same time. This can be easily done by the main applicant – the person applying for the **specific** work permit - by adding their partner when applying. By doing this, the main applicant will be leading both applications and will need to add some documents to its own application and also some documents will be asked for the partner's application. 

The documents that will be added to the main applicants' **specific** work permit applicant will be:

* Use of a family member representative (this document authorizes that the main applicant will be the partner's representative)
* Statutory declaration of common-law union
    * Married couples: Marriage certificate
    * Un-married couples: Proof of living together at least for a year
    
For the **open** permit of the partner, you will need a

* passport photograph
* other short forms

The system seems to be pretty open to these joint applications. However, the more labour intensive application will be for the main applicant as you have to provide many more letters for the application of the **specific** work permit.

Such kind of a joint application will cost approximately $450 in total, including the permits and any other fees associated to it.

---

> **Tip**: We recommend you to bring a buffer of cash to survive for at least a month or two, because processing times until UQÀM makes the first payment takes time!

> **Tip**: Finding apartments from abroad is tricky. Sometimes students/post-docs leave at the same time as you arrive, so you can ask around. Otherwise, we recommend to book an Air Bnb for a month and explore which neighbourhood you like.

---

## After arrival
### 1. Sign contract
?

---

### 2. Get a Social insurance number (SIN)
You will need to get your social insurance number (SIN) and provide it to UQÀM. To get your SIN, go to:

>*Service Canada*
>
>*Guy-Favreau Complex, Suite 034*
>
>*200 René-Lévesque Boulevard West*
>
>*Open Mon-Fri 8:30 am – 4 pm*

Accessible through the underground from Place-des-arts (Green Line) or Place-d’Armes (Orange line) metro stations.

You will have to bring:

* your passport with the work permit
* fill out their form

Check further information [here](https://www.canada.ca/en/employment-social-development/services/sin/before-applying.html#primary).

> **Tip**: Whenever you renew your work permit, you need to update your social insurance number, too!

---

### 3. Student Card
As a post-doc, you get a student card and get access to student benefits and the gym. Make sure to bring your passport and they will make a picture on-site. Consult opening hours [here](http://ech.uqam.ca/2016-08-02-22-07-10/carte-uqam/horaire-et-coordonnees.html). The place is one floor down of the UQÀM registrariat in the UQÀM main campus.

---

### 4. Access to UQÀM mail
?

---

### 5. Opus card for metro
Unfortunately, post-docs are not elgibile for the student price of the OPUS card. You need to pay the general annual or monthly pass.

---

### 6. Health insurance

As a post-doc or temporary research intern (have a specific work permit) you can apply to the provincial health insurance called **RAMQ** (Régie de l'assurance maladie du Québec). This is a free medical insurance offered by Québec but covers you across Canada. You will get free assistance in specific medical centers but, unless an emergency occurs, you will need to wait many hours to be attended.

To obtain the RAMQ card, you need to personally assist to:

>*RAMQ desk*
>
>*425 Boulevard de Maisonneuve O, 3rd floor, Office 301*

Make sure to print and fill the application form and bring the necessary documents listed on the [RAMQ website](https://www.ramq.gouv.qc.ca/en/citizens/health-insurance/registration/Pages/how-to-register.aspx). Documents include:

* Social Security Number
* Passport
* Work Permit

Upon arrival you have to ask for an appointment and wait – waiting is usually long, around 3 hours.
Be aware that you will have to wait more than 14 days to receive your insurance card. Once you get your RAMQ, you’ll have to wait for a further 3 months until it becomes active. Make sure to be covered by a travel insurance from your country of origin (e.g. [blue cross](http://www.bluecross.ca/en/index.html)) or take a private insurance (e.g. [Desjardins](https://www.desjardinslifeinsurance.com/en/individual-insurance/life-health-disability-insurance/health-disability-insurance/healthcare-insurance)) to live through this un-covered period without being worried constantly.

---

### 7. Driving licence
As a post-doc you are only allowed to drive with your driving license from your original country up to six months (count the days since your arrival in Québec).
The first day after six months have passed, you will be driving illegally. Make sure to exchange your licence. If your driving licence is from a certain country, you can easily exchange your driving licence. You need to bring:

* foreign driver's licence
* work permit
* Proof of residency in Québec
* Proof of residency in the country in which your licence was issued if you obtained your licence within the previous 3 years
* Translation of your driver's licence, if it is written in a language other than French or English

You need to schedule an appointment by telephone.

If your country does not have a jurisdictional agreement, you need to pass a test. Get also an appointment for this.

Find the details at [SAAQ](https://saaq.gouv.qc.ca/en/drivers-licences/foreign-drivers-licence/).

---

# Universal
## Wi-fi at UQÀM
Depending on what device your using, the set-up of wi-fi will differ. Essentially, you will be using **eduroam**. Follow the instructions provided [here](https://servicesinformatiques.uqam.ca/services/R%C3%A9seau%20sans%20fil). There is a section for each operating system (e.g. Windows, Mac, Android, iPhone etc.).

If you have trouble with connecting to the wifi when you just arrive, contact Alice Parkesor Sara for a temporary visitor wifi login before you can connect to eduroam.
---

## Access to labs and keys
We have several labs that are shared among the universities at UQÀM. To get access to the labs, get the key **NE 91** from Katherine. You can also get keys to other labs and offices. Our key manager is located in the RC floor of the SB-building. Usually, a deposit of around $10 for each key is necessary. You will get this money back, once you give the key back.

Some labs/rooms have calendars to manage it's usage:

* [GRIL analytical equipment](https://teamup.com/ks4a7d3d6d5515ab77/)
* [Seminar/Lunch room](https://teamup.com/ks4a80cc0616719148)
* [Molecular Lab Extraction bench](https://calendar.google.com/calendar?cid=ZGo0a3NlNGR1NHB2OG9yaW52M29jbGR1bm9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)
* [Molecular Lab PCR bench](https://calendar.google.com/calendar?cid=NWs3YnA1OHBoMmppMWlyZnZsZ2JibDZscXNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)
* [Autoclave (3rd floor)](https://bio.uqam.ca/reservations/)

Make sure to follow the calendar. Usually, it's first come first serve but if you have urgent schedules ask the people if they can reschedule for you.

Other equipment/trucks that are based on reservation can be found [here](https://gril.uqam.ca/reservations/).

---

## Freely available software
There is a suit of software that you can access through UQÀM (e.g. JMP, SPSS etc.). To see which programs you can download check [here](https://servicesinformatiques.uqam.ca/services/Laboratoire%20virtuel). You can log-in to the  [*virtual lab*](https://www.bureauvirtuel.uqam.ca/Citrix/XenAppSitel/site/default.aspx) to download the software.

To get access to **ArcGIS** send an email to [geolab@uqam.ca](geolab@uqam.ca) to ask for the instructions.

Other universally open-access software are [R](https://www.r-project.org/) for statistical computing, [QGIS](https://qgis.org/en/site/) for maps and geographical computing and [Mendeley](https://www.mendeley.com/?interaction_required=true) for organising your references.

---

## VPN
Only employees can access the UQÀM VPN (due to security reasons). For post-docs, to get VPN follow the instructions [here](https://servicesinformatiques.uqam.ca/services/R%C3%A9seau%20priv%C3%A9%20virtuel%20(VPN)).

For students, if you need to get access to papers:

1. **At UQÀM**:
If you're using the Wi-fi of the university, you will be automatically directed to the UQÀM library services when downloading papers.

2. **Outside of UQÀM**:
You need to set up a link to the UQÀM library in your browser. Refer to instructions [here](https://bibliotheques.uqam.ca/ressources-electroniques/).

You will be asked for your *code MS* and *password* every time you access a non open-access resource.

If you want to use another article search engine besides *Google Scholar*. For example, *Scopus* use this [link](https://www-scopus-com.proxy.bibliotheques.uqam.ca:2443/search/form.uri?display=basic&clear=t&origin=searchauthorlookup&txGid=1a6400297ca89390d62f31a08e8764a5) (URL includes the library proxy) to use the search engine through the UQÀM library.

Some journals are not accessible through our university. Then [*Sci-hub*](sci-hub.tw/) comes to rescue.

---

## Seminars
We have two regular seminars every week. Departmental ecology seminars on Wednesdays and a limnology seminar on Fridays. Both at 12:15 pm, bring your lunch.

Here are the mailing lists for both seminars:

* [Ecology](https://uqam.us8.list-manage.com/subscribe?u=fa73400fff41935863934c99f&id=ff78da2fd3)
* [Midi-aquatique](https://uqam.us10.list-manage.com/subscribe?u=51cc82ab57c93800bfccbdc4c&id=b723fef13c)

And google calendars:

* [Ecology](https://calendar.google.com/calendar/embed?src=jv0dl4buninp7e0ioctqt8m28g%40group.calendar.google.com&ctz=America%2FToronto)
* [Midi-aquatique](https://calendar.google.com/calendar?cid=YzM0bnNmcnAxcWxoZm8ycTc5NTAyNXMzMHNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

Additionally, our laboratories are part of an interuniversity limnology society of Quebec called GRIL. We have several GRIL groups at UQÀM and there is also a [mailing list]((https://us10.list-manage.com/subscribe?u=51cc82ab57c93800bfccbdc4c&id=a786c35733)) for this that you can subscribe to.

---

## GRIL member
We are part of an interuniversity limnology research group called [GRIL](https://oraprdnt.uqtr.uquebec.ca/pls/public/gscw030?owa_no_site=543). And usually every student and post-doc joins this society. We also have an annual symposium around March and a workshop in autumn.

To join the GRIL access the [Intranet](https://oraprdnt.uqtr.uquebec.ca/pls/public/gscw030?owa_no_site=5451). The password is *GRILdoc*. Go to "Application form for GRIL student membership" and fill in the necessary information.

If you're more interested in the GRIL, we have several groups that are part of GRIL at UQÀM and you can check the (UQÀM-GRIL website)[https://gril.uqam.ca/].

---

## Expense Reports
Whenever you go to a conference or spend money during a research activity (e.g. attending workshops or internships), you need to file expense reports. Make sure to keep all your receipts. You will need to attach them using transparent tape on seperate letter-size papers (one-sided) so UQÀM can easily scan them. With all your receipts separately and visibly taped on paper, you will need to fill an "Expense report" and give this to Alice or directly send/bring it to the finances office of UQÀM.

If you don't have enough money in your private bank account to pay for large amounts such as a plane ticket to a conference location, you can ask for an advance payment or book the plane ticket through a travel agency that UQÀM uses.

---

## Taxes
Once a year everyone has to file income taxes.

While students do not have to pay income taxes, it is advised to file the taxes every year. You will get some money every year and if you plan to stay afterwards in Québec, you will even get more money back.

---

### Students
To get your tax slips, go to these pages:

**Portail étudiant**

Go to *'Relevés d'impôts'*. You will find:

* T2202A (federal)
* Relevé 8 (provincial)

[**Human resources**](https://rhu.uqam.ca/index.aspx?id=p258)

Go to *'Feuillets fiscaux'* -> 'Sans Code MS'. You will need:

* name, surname
* birthday
* last three numbers of your SIN (or NAS)
* postal adresse of your address **OR** 4 last numbers of your phone

You will find:

* T4A (federal)
* Relevé 1 (provincial)

>To help you file the report you can use [UFile](https://www.ufile.ca/), which is free for students with the code: CFS1981 

There are also seminars at UQÀM that prepare you for filing you taxes (in French). Keep an eye on your UQÀM email inbox if you're interested.

Other helpful links:

* [Tax Guide for Newcomers](https://www.canada.ca/en/revenue-agency/services/tax/international-non-residents/individuals-leaving-entering-canada-non-residents/newcomers-canada-immigrants.html)
* [Gov. of Canada on Taxes for International Students](https://www.canada.ca/en/revenue-agency/services/tax/international-non-residents/individuals-leaving-entering-canada-non-residents/international-students-studying-canada.html)
* [Determining your residency status](https://www.canada.ca/en/revenue-agency/services/forms-publications/forms/nr74.html)
* [Finding free tax clinics near you](https://www.canada.ca/en/revenue-agency/services/tax/individuals/community-volunteer-income-tax-program.html)

---

### Post-docs
?

---

## French classes
Since 2019, students are also allowed to take French classes offered for free by the Government. Those classes are usually intense (three days a week) and get full very quickly. Check the [website](https://www.immigration-quebec.gouv.qc.ca/en/french-language/index.html) and register early enough.

Other schools that are relatively affordable:

* [Milton Parc](https://www.amilia.com/store/en/armp/shop/programs/49020)
* [YMCA](https://www.ymcalanguages.com/en/YMCA-Language-School/Home)
* [Dawson College](https://www.dawsoncollege.qc.ca/ctd/course-category/languages/)

If your French level is already more advanced. There are advanced courses offered by [UQÀM](https://langues.uqam.ca/francais/), too. If you're thinking of applying for a permanent residency eventually, they also offer courses to prepare for the exam.

---

## Other resources
### At UQÀM
* Food court in the PK-building (is not particularly cheap)
* [Fractal](http://aessuqam.org/Cafe-Fractal) (Student coffee shop in the SH-building)
* [BQÀM](http://bqam.org/): A free bicycle workshop. Experts are there to help you fix your bike but you have to do the work. They also sell bicycle parts in case you need to repair your bike.

### Websites to look for apartments and furniture

* [Kijiji](https://www.mcgill.ca/studentaid/files/studentaid/cheap_sheet_march_2018.pdf)
* [Craigslist](https://montreal.craigslist.org/)
* Facebook groups (e.g. [PVT](https://www.facebook.com/groups/pvtistesamontrealpetitesannoncesofficiel/), [Logements à louer](https://www.facebook.com/groups/516817751854925/), [Apartments for rent](Logements à Louer, Montréal, Apartments for Rent))

### Cheap stores

* [Bulk Barn](http://www.bulkbarn.ca/en/Home) get un-packaged food.
* [PA Supermarché](supermarchepa.com) cheaper vegetables and cheese.
* Segal's market
* Provigo close to UQÀM has a point system called PC optimum. Students get 20% points on any purchase from Mon-Wed. If you do all your groceries there, you can get $10-20 cash back each month.
* [Winners](https://www.winners.ca/en) Clothes outlet stores

### Second hand stores

* [Village de Valeurs](valuevillage.com)
* [Renaissance](https://www.renaissancequebec.ca/en)
* [Salvation army](https://salvationarmy.ca/quebec/montreal-thrift-store-2/)

There is a great ['cheap list'](https://www.mcgill.ca/studentaid/files/studentaid/cheap_sheet_march_2018.pdf) by McGill. Many things on the list are only for McGill students, but others are for everyone!